# Generated by Django 6.0.5 on 2026-05-06 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_without_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='boardcolumn',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Колонка доски', 'verbose_name_plural': 'Колонки досок'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'verbose_name': 'Участие в проекте', 'verbose_name_plural': 'Участия в проектах'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-spent_on', '-id'], 'verbose_name': 'Запись учёта времени', 'verbose_name_plural': 'Учёт времени'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-release_date', 'name'], 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['status_id', 'position', 'id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='workitemrelation',
            options={'verbose_name': 'Связь между задачами', 'verbose_name_plural': 'Связи между задачами'},
        ),
        migrations.AlterField(
            model_name='board',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Доска по умолчанию'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(default='Основная', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.board', verbose_name='Доска'),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.workitem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('viewer', 'Наблюдатель'), ('member', 'Участник'), ('developer', 'Разработчик'), ('manager', 'Менеджер'), ('admin', 'Админ проекта')], default='member', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрывает задачу'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='status',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='status',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='minutes',
            field=models.PositiveIntegerField(verbose_name='Минуты'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='spent_on',
            field=models.DateField(verbose_name='Дата работы'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.workitem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='version',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Релиз закрыт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='version',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_work_items', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='item_type',
            field=models.CharField(choices=[('task', 'Задача'), ('bug', 'Баг'), ('feature', 'Фича'), ('epic', 'Эпик')], db_column='type', default='task', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в колонке'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='core.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='core.version', verbose_name='Целевая версия'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='workitemrelation',
            name='from_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_out', to='core.workitem', verbose_name='Исходная задача'),
        ),
        migrations.AlterField(
            model_name='workitemrelation',
            name='relation_type',
            field=models.CharField(choices=[('blocks', 'Блокирует'), ('relates', 'Связана с'), ('duplicates', 'Дубликат'), ('precedes', 'Предшествует (Гант FS)')], max_length=20, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='workitemrelation',
            name='to_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_in', to='core.workitem', verbose_name='Связанная задача'),
        ),
    ]
