# Generated by Django 6.0.5 on 2026-05-06 18:33

import django.db.models.deletion
from django.db import migrations, models


def seed_default_themes(apps, schema_editor):
    Theme = apps.get_model("core", "Theme")
    Theme.objects.update_or_create(
        slug="dark",
        defaults={
            "name": "Тёмная",
            "is_active": True,
            "sort_order": 0,
            "is_default_for_unassigned": True,
        },
    )
    Theme.objects.update_or_create(
        slug="light",
        defaults={
            "name": "Светлая",
            "is_active": True,
            "sort_order": 10,
            "is_default_for_unassigned": False,
        },
    )
    Theme.objects.exclude(slug="dark").update(is_default_for_unassigned=False)
    Theme.objects.filter(slug="dark").update(is_default_for_unassigned=True)


def unseed_default_themes(apps, schema_editor):
    Theme = apps.get_model("core", "Theme")
    Theme.objects.filter(slug__in=["dark", "light"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ru_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Сейчас поддерживаются палитры в CSS только для значений «dark» и «light». Другие slug можно завести вперёд, но стили появятся после доработки CSS.', max_length=64, unique=True, verbose_name='Идентификатор темы')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна для выбора')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_default_for_unassigned', models.BooleanField(default=False, help_text='Применяется, если у пользователя не указана своя тема. Можно отметить только у одной темы (при сохранении остальные снимаются).', verbose_name='Стандартная для пользователей без темы')),
            ],
            options={
                'verbose_name': 'Тема оформления',
                'verbose_name_plural': 'Темы оформления',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.RunPython(seed_default_themes, unseed_default_themes),
        migrations.AddField(
            model_name='user',
            name='preferred_theme',
            field=models.ForeignKey(blank=True, help_text='Пусто — для пользователя действует общая тема по умолчанию (см. «Стандартная для пользователей без темы» в списке тем).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.theme', verbose_name='Тема оформления'),
        ),
    ]
