# Generated by Django 6.0.5 on 2026-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Объект вида {"--bg0": "#05060a", "--text": "#e2e8f0"} — ключи как в :root. Пусто — только базовая палитра по slug (dark/light).', verbose_name='Переменные CSS'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(help_text='Базовая палитра из файла стилей: «dark» или «light». Для своих имён задайте ниже «Переменные CSS» — тогда оформление задаётся без правок кода.', max_length=64, unique=True, verbose_name='Идентификатор темы'),
        ),
    ]
