# Generated by Django 6.0.5 on 2026-05-06 18:48

from django.db import migrations, models

SAKURA_CSS_VARIABLES = {
    "--bg0": "#fff5f9",
    "--bg1": "#ffe8f2",
    "--bg2": "#ffdaeb",
    "--surface": "rgba(255, 252, 254, 0.92)",
    "--surface-solid": "#fffafd",
    "--border": "rgba(236, 72, 153, 0.14)",
    "--border-strong": "rgba(219, 39, 119, 0.24)",
    "--text": "#6b2d4f",
    "--text-muted": "#a8557c",
    "--text-dim": "#c084a8",
    "--accent": "#e11d73",
    "--accent-bright": "#f472b6",
    "--accent-deep": "#be185d",
    "--accent-glow": "rgba(244, 114, 182, 0.45)",
    "--success": "#0d9488",
    "--warning": "#ca8a04",
    "--danger": "#dc2626",
    "--shadow-sm": "0 2px 14px rgba(219, 39, 119, 0.09)",
    "--shadow-md": "0 18px 52px rgba(236, 72, 153, 0.15)",
    "--shadow-glow": "0 0 72px rgba(251, 207, 232, 0.5)",
}


def seed_sakura_and_bases(apps, schema_editor):
    Theme = apps.get_model("core", "Theme")
    Theme.objects.filter(slug="dark").update(data_theme_base="dark")
    Theme.objects.filter(slug="light").update(data_theme_base="light")
    Theme.objects.update_or_create(
        slug="sakura",
        defaults={
            "name": "Сакура",
            "css_variables": SAKURA_CSS_VARIABLES,
            "is_active": True,
            "is_exclusive": True,
            "data_theme_base": "light",
            "sort_order": 50,
            "is_default_for_unassigned": False,
        },
    )


def remove_sakura(apps, schema_editor):
    Theme = apps.get_model("core", "Theme")
    Theme.objects.filter(slug="sakura").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_theme_css_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='data_theme_base',
            field=models.CharField(choices=[('dark', 'Тёмная ветка'), ('light', 'Светлая ветка')], default='dark', help_text='Для slug не «dark»/«light»: какой режим вёрстки использовать (светлые/тёмные правила в CSS).', max_length=5, verbose_name='База интерфейса (CSS)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Не попадает в общий список тем и в личный кабинет; переключатель тем в шапке её обходит. Назначить может только сотрудник в разделе «Сотрудники» или Django admin.', verbose_name='Только по назначению администратора'),
        ),
        migrations.RunPython(seed_sakura_and_bases, remove_sakura),
    ]
