# Generated by Django 6.0.5 on 2026-05-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorateSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('group', 'Группа'), ('department', 'Отдел')], default='group', max_length=16, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='core.directorate', verbose_name='Дирекция')),
            ],
            options={
                'verbose_name': 'Группа/отдел дирекции',
                'verbose_name_plural': 'Группы/отделы дирекций',
                'ordering': ['directorate__sort_order', 'sort_order', 'kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subdivision',
            field=models.ForeignKey(blank=True, help_text='Опционально: группа или отдел внутри выбранной дирекции.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.directoratesubdivision', verbose_name='Группа/отдел'),
        ),
        migrations.CreateModel(
            name='DirectorateSubdivisionChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.directoratesubdivision', verbose_name='Группа/отдел')),
            ],
            options={
                'verbose_name': 'Сообщение чата группы/отдела',
                'verbose_name_plural': 'Сообщения чата групп/отделов',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='directoratesubdivision',
            constraint=models.UniqueConstraint(fields=('directorate', 'kind', 'name'), name='uniq_subdivision_dir_kind_name'),
        ),
    ]
