# Generated by Django 6.0.5 on 2026-05-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subdivisions_and_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoratechatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='directorate_chat/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='directoratechatmessage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
    ]
