# Generated by Django 6.0.5 on 2026-05-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_projectchat_attachment_and_body_blank'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workitemstatushistory',
            new_name='core_workit_work_it_6bee51_idx',
            old_name='core_workit_work_it_3f7f47_idx',
        ),
    ]
