# Generated by Django 6.0.5 on 2026-05-08 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_core_workit_work_it_3f7f47_idx_core_workit_work_it_6bee51_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_item_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кем загружено')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.workitem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вложение задачи',
                'verbose_name_plural': 'Вложения задач',
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['work_item', 'uploaded_at'], name='core_workit_work_it_453ea7_idx')],
            },
        ),
    ]
